openapi: 3.0.3
x-optic-path-ignore:
  - '**/**.ico'
info:
  title: Untitled service
  version: 1.0.0
paths:
  /todos:
    get:
      responses:
        '200':
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        completed_at:
                          type: string
                        color:
                          type: string
                      required:
                        - name
                        - color
                required:
                  - todos
