version: 2
updates:
  - package-ecosystem: npm
    directory: /
    allow:
      - dependency-type: production
    schedule:
      interval: monthly
    rebase-strategy: auto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - opticdev/infra
    rebase-strategy: auto
