openapi: 3.0.3
info:
  title: a spec
  description: The API
  version: 0.1.0
paths:
  /books:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: ['name', 'price', 'author_id']
              properties:
                name:
                  type: string
                price:
                  type: string
                author_id:
                  type: string
      "responses": {}
    get:
      # a comment about something
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                # use the refs here
                $ref: "#/components/schemas/GetBooks200ResponseBody"
components:
  schemas:
    # this is a schema
    GetBooks200ResponseBody:
      type: object
      properties:
        books:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              author_id:
                type: number
              status:
                type: string
                enum:
                  - ready
                  - not_ready
              price:
                type: number
                maximum: 6
                minimum: 2
            required:
              - id
              - author_id
