plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: "*"
  tcompare@*:
    dependencies:
      diff: "*"
  treport@*:
    dependencies:
      tap-yaml: "*"