# Mute fetch-not-cached - we do not use zero-installs so this will
# always show up on fresh builds
# https://yarnpkg.com/advanced/error-codes#yn0013---fetch_not_cached
logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
