# Mute fetch-not-cached - we do not use zero-installs so this will
# always show up on fresh builds
# https://yarnpkg.com/advanced/error-codes#yn0013---fetch_not_cached
logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
