# https://taskfile.dev/#/installation
version: "3"

tasks:
  default:
    desc: Perform a clean build
    cmds:
      - task: setup
      - task: clean
      - task: build

  setup:
    desc: Install dependencies
    cmds:
      - yarn install

  build:
    desc: Build
    cmds:
      - yarn workspaces foreach -pv --topological-dev --no-private run ws:build

  clean:
    desc: Clean
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:clean

  test:
    desc: Test
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:test

  openapi-diff:docker:build:
    desc: Build the interactive baseline image used to generate OpenAPI specs
    dir: projects/openapi-diff
    env:
      TAG: '{{default "local" .TAG}}'
    cmds:
      - docker build {{.CLI_ARGS}} optic-baseline:$TAG .
