version: '3'

dotenv:
  - .env

env:
  DOCKER_REGISTRY: 513974440343.dkr.ecr.us-east-1.amazonaws.com
  NODE_ENV: '{{default "development" .NODE_ENV}}'

includes:
  optic-engine-native:
    taskfile: workspaces/optic-engine-native/Taskfile.yml
  ui-v2:
    taskfile: workspaces/ui-v2/Taskfile.yml
    dir: workspaces/ui-v2
  regression:
    taskfile: taskfiles/regression-tests/Taskfile.yml
  release:
    taskfile: taskfiles/release/Taskfile.yml
  release:side-channel:
    taskfile: taskfiles/release/side-channel/Taskfile.yml
  utility:
    taskfile: taskfiles/utility/Taskfile.yml
  verdaccio:
    taskfile: docker/private-npm-registry/Taskfile.yml
    dir: docker/private-npm-registry
  website:
    taskfile: website/Taskfile.yml
    dir: website

tasks:
  postpull:
    deps: ['workspaces:clean', 'workspaces:build']
  workspaces:setup:
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: 'true'
    cmds:
      - yarn install
      - yarn run husky install
    generates:
      - .yarn/**/*
      - yarn.lock
    sources:
      - workspaces/*/package.json
      - package.json
      - yarn.lock

  workspaces:setenv:
    desc: Ensure workspace projects have .env files
    vars:
      FLAGS_FILE: '{{.FLAGS_FILE}}'
    cmds:
      - |
        if [[ -n "$FLAGS_FILE" ]]
        then
          echo "Feature flags found ($FLAGS_FILE), copying to packages for build and runtime."
          cp $FLAGS_FILE .env
          cp $FLAGS_FILE workspaces/local-cli/.env
          cp $FLAGS_FILE workspaces/cli-server/.env
          cp $FLAGS_FILE workspaces/cli-scripts/.env
          cp $FLAGS_FILE workspaces/optic-engine/.env
          cp $FLAGS_FILE workspaces/optic-engine-native/.env
          cp $FLAGS_FILE workspaces/ui-v2/.env.production.local
        else
          echo "Please specify the FLAGS_FILE environment variable"
          exit 1
        fi

  workspaces:test:
    desc: Test Yarn workspaces
    cmds:
      - yarn wsrun --stages --report --fast-exit --exclude-missing ws:test

  workspaces:build:
    desc: Build Yarn workspaces
    deps: ['workspaces:setup']
    cmds:
      - yarn wsrun --stages --report --fast-exit --exclude-missing ws:build

    sources:
      - !workspaces/*/build/**/*
    generates:
      - workspaces/optic-engine-wasm/browser/**/*
      - workspaces/optic-engine-wasm/build/**/*
      - workspaces/optic-engine-wasm/target/**/*
      - workspaces/*/build/**/*

  workspaces:build:ci:
    desc: CI workflow
    vars:
      FLAGS_FILE: '{{.FLAGS_FILE}}'
    cmds:
      - task: workspaces:setup
      - task: workspaces:clean
      - task: workspaces:setenv
        env:
          FLAGS_FILE: '{{.FLAGS_FILE}}'
      - task: workspaces:build
      - task: workspaces:test
      - task: flush-to-disk

  workspaces:clean:
    desc: Remove previous build artifacts
    cmds:
      - yarn wsrun --report --fast-exit --exclude-missing ws:clean

  npm:publish:
    deps:
      - workspaces:build
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: 'false'
    cmds:
      - yarn install

  flush-to-disk:
    cmds:
      - sudo /usr/sbin/purge
    status:
      - uname -a | grep -qv Darwin

  docker:slack-notifier:
    desc: Posts a message to Slack
    summary: |
      Posts a docker build announcement to Slack. To disable announcements
      unset SLACK_WEBHOOK.

      Expected env:
        * REPO — the Docker image repository
        * SLACK_WEBHOOK — a Slack webhook URL
        * TAG — the Docker image tag
        * USER — the user to direct the message at
    vars:
      MESSAGE: '{{.USER}}: `{{.REPO}}:{{.TAG}}` was pushed to our Docker registry.'
    env:
      DATA: '{"text":"{{.MESSAGE}}"}'
    cmds:
      - echo $DATA
      - 'curl -X POST -H "Content-type: application/json" --data "$DATA" $SLACK_WEBHOOK'
    status:
      - test -z $SLACK_WEBHOOK
