# https://taskfile.dev/#/installation
version: "3"

includes:
  openapi-utilities:
    taskfile: projects/openapi-utilities/Taskfile.yml
    dir: projects/openapi-utilities

tasks:
  default:
    desc: Perform a clean build
    cmds:
      - task: setup
      - task: clean
      - task: build

  setup:
    desc: Install dependencies
    cmds:
      - yarn install

  build:
    desc: Build
    cmds:
      - yarn workspaces foreach -pv --topological-dev --no-private run ws:build

  clean:
    desc: Clean
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:clean

  test:
    desc: Test
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:test

  update-snapshots:
    desc: Update snapshots
    cmds:
      - yarn workspaces foreach -pv --no-private run ws:test -u

  publish:
    desc: "Publish built artifacts. Passes CLI_ARGS to 'npm publish'"
    cmds:
      - yarn workspaces foreach -v --no-private npm publish --access public {{.CLI_ARGS}}
