version: "3"

dotenv:
  - .env

env:
  DOCKER_REGISTRY: 513974440343.dkr.ecr.us-east-1.amazonaws.com

includes:
  diff-engine:
    taskfile: workspaces/diff-engine/Taskfile.yml
  ui:
    taskfile: workspaces/ui/Taskfile.yml
    dir: workspaces/ui
  regression:
    taskfile: taskfiles/regression-tests/Taskfile.yml
  release:
    taskfile: taskfiles/release/Taskfile.yml
  release:side-channel:
    taskfile: taskfiles/release/side-channel/Taskfile.yml
  verdaccio:
    taskfile: docker/private-npm-registry/Taskfile.yml
    dir: docker/private-npm-registry

tasks:
  workspaces:setup:
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: "true"
    cmds:
      - yarn install

  workspaces:build:
    desc: Build Yarn workspaces
    deps: ["workspaces:setup"]
    cmds:
      - yarn wsrun --stages --report --fast-exit --exclude-missing ws:build
    sources:
      - !workspaces/*/build/**/*
    generates:
      - workspaces/diff-engine-wasm/lib/**/*
      - workspaces/diff-engine-wasm/engine/browser/**/*
      - workspaces/diff-engine-wasm/engine/build/**/*
      # - workspace/diff-engine-wasm/engine/target/**/* # do we need this?
      - workspaces/*/build/**/*

  workspaces:build:ci:
    desc: CI workflow
    cmds:
      - task: workspaces:setup
      - task: workspaces:clean
      - task: workspaces:build
      - task: flush-to-disk

  workspaces:clean:
    desc: Remove previous build artifacts
    cmds:
      - yarn wsrun --stages --report --fast-exit ws:clean

  spec:build:
    dir: workspaces/ui
    env:
      PUBLIC_URL: "https://apidocs.o3c.info"
      CI: "false"
    cmds:
      - yarn build-spec

  npm:publish:
    deps:
      - workspaces:build
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: "false"
    cmds:
      - yarn install

  flush-to-disk:
    cmds:
      - sudo /usr/sbin/purge
    status:
      - uname -a | grep -qv Darwin

  docker:slack-notifier:
    desc: Posts a message to Slack
    summary: |
      Posts a docker build announcement to Slack. To disable announcements
      unset SLACK_WEBHOOK.

      Expected env:
        * REPO — the Docker image repository
        * SLACK_WEBHOOK — a Slack webhook URL
        * TAG — the Docker image tag
        * USER — the user to direct the message at
    vars:
      MESSAGE: "{{.USER}}: `{{.REPO}}:{{.TAG}}` was pushed to our Docker registry."
    env:
      DATA: '{"text":"{{.MESSAGE}}"}'
    cmds:
      - echo $DATA
      - 'curl -X POST -H "Content-type: application/json" --data "$DATA" $SLACK_WEBHOOK'
    status:
      - test -z $SLACK_WEBHOOK
