// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package optic_shape_hash.shapehash

object ShapehashProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      optic_shape_hash.shapehash.FieldDescriptor,
      optic_shape_hash.shapehash.ShapeDescriptor
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg9zaGFwZWhhc2gucHJvdG8SEG9wdGljX3NoYXBlX2hhc2gibwoPRmllbGREZXNjcmlwdG9yEhoKA2tleRgBIAEoCUII4j8FE
  gNrZXlSA2tleRJACgRoYXNoGAIgASgLMiEub3B0aWNfc2hhcGVfaGFzaC5TaGFwZURlc2NyaXB0b3JCCeI/BhIEaGFzaFIEaGFza
  CLnAgoPU2hhcGVEZXNjcmlwdG9yEk4KBHR5cGUYASABKA4yLy5vcHRpY19zaGFwZV9oYXNoLlNoYXBlRGVzY3JpcHRvci5Qcmlta
  XRpdmVUeXBlQgniPwYSBHR5cGVSBHR5cGUSRgoGZmllbGRzGAIgAygLMiEub3B0aWNfc2hhcGVfaGFzaC5GaWVsZERlc2NyaXB0b
  3JCC+I/CBIGZmllbGRzUgZmaWVsZHMSQwoFaXRlbXMYAyADKAsyIS5vcHRpY19zaGFwZV9oYXNoLlNoYXBlRGVzY3JpcHRvckIK4
  j8HEgVpdGVtc1IFaXRlbXMSIAoFcnVsZXMYBCADKAlCCuI/BxIFcnVsZXNSBXJ1bGVzIlUKDVByaW1pdGl2ZVR5cGUSCgoGT0JKR
  UNUEAASCQoFQVJSQVkQARIKCgZTVFJJTkcQAhIKCgZOVU1CRVIQAxILCgdCT09MRUFOEAQSCAoETlVMTBAFYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}