name: optic
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  diff-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Spec
        # TODO: Replace this line with your generation script
        run: generate-spec.sh

      - uses: opticdev/action@v1
        with:
          # Your Optic Cloud Token
          optic_token: ${{ secrets.OPTIC_TOKEN }}

          # A GitHub token with access to create comments on pull requests
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # If true, standard check failures will cause this action to fail.
          # If false, standard check failures will show in PR comments and
          # in Optic Cloud but will not cause the action to fail
          standards_fail: %standards_fail

          # TODO: Modify the match argument to be the name of your spec. If you have
          # more than one spec, separate them with commas (openapi.yml,other.yml)
          additional_args: --generated --match openapi-spec.yml
          compare_from_pr: cloud:default
          compare_from_push: cloud:default
