openapi: 3.0.3
info:
  title: a spec
  description: The API
  version: 0.1.0
paths:
  /filler_route:
    post:
      operationId: create
      responses:
        "201":
          description: Created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    format: uuid
                    example: d5b640e5-d88c-4c17-9bf0-93597b7a1ce2
x-optic-url: https://app.o3c.info/organizations/88c4a2a7-b90f-431e-8017-fddcb0d78b46/apis/9g0dLm4PveYM7ZHNpCy9r
