App:
  type: object
  properties:
    type:
      type: string
    id:
      type: string
      format: uuid
    attributes: { $ref: '#/AppAttributes' }
    links: { $ref: '../common.yaml#/Links' }
  required: ['type', 'id', 'attributes']
  additionalProperties: false

AppAttributes:
  type: object
  properties:
    name:
      description: The name given to the app.
      type: string
    clientId:
      description: The oauth2 client id for the app.
      type: string
      format: uuid
    redirectUris:
      type: array
      description: The provided redirect URIs for the app.
      items:
        type: string
    scopes:
      type: array
      description: The scopes this app is allowed to request during authorization.
      items:
        type: string
    isPublic:
      type: boolean
      description: A boolean to indicate an app is publicly available.
  required: ['name', 'clientId', 'redirectUris', 'scopes', 'isPublic']
