openapi: "3.0.0"
info:
  title: Recursive Example
  description: >-
    Documentation of services
  version: '1.0'
paths:
  /api/example:
    get:
      summary: Get example
      description: example
      operationId: GetExample
      responses:
        '200':
          description: Successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

      deprecated: false
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        name:
          type: string
          description: name of the example
        id:
          type: string
          description: identifier of the example
        organization:
          $ref: '#/components/schemas/Organization'
    Organization:
      title: Organization
      type: object
      properties:
        name:
          type: string
          description: name of the example
        id:
          type: string
          description: identifier of the example
        user:
          $ref: '#/components/schemas/User'
