openapi: "3.0.0"
info:
  title: Direct Recursive Example
  description: >-
    Self-referencing circular example
  version: '1.0'
paths:
  /user/details:
    get:
      tags:
        - User
      summary: Get User Details
      description: Get User Details
      operationId: GetUserDetails
      responses:
        '200':
          description: Successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
      deprecated: false
    post:
      tags:
        - User
      summary: Get User Details
      description: Get User Details
      operationId: GetUserDetails
      requestBody:
        description: Successful operation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDetails'
      responses:
        '200':
          description: Successful operation
          headers: {}
          content: {}
      deprecated: false
components:
  schemas:
    UserDetails:
      title: UserDetails
      type: object
      properties:
        name:
          type: string
          description: User name
          example: Joe Mauma
        email:
          type: string
          description: joe@maumas-house.net
        id:
          type: number
          description: Unique ID
        best_friend:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UserDetails'
tags:
  - name: UserDetails