openapi: '3.1.0'
info:
  title: 'some thing'
  version: 'v0'
paths:
  /example:
    get:
      requestBody:
      responses:
        200:
          description: 'some thing'
          content:
            application/json:
              schema:
                type: ['object', 'array']
                items:
                  allOf:
                    - type: object
                      properties:
                        a:
                          type: string
                    - type: object
                      properties:
                        b:
                          type: number
                        c:
                          type: string
                    - type: object
                      properties:
                        d:
                          allOf:
                            - type: 'object'
                              properties:
                                a:
                                  type: string
                            - type: 'object'
                              properties:
                                b:
                                  type: string
                        e:
                          type: string
                properties:
                  inside_object:
                    allOf:
                      - type: object
                        properties:
                          a:
                            type: string
                      - type: object
                        properties:
                          b:
                            type: number
                          c:
                            type: string
                      - type: object
                        properties:
                          d:
                            allOf:
                              - type: 'object'
                                properties:
                                  a:
                                    type: string
                              - type: 'object'
                                properties:
                                  b:
                                    type: string
                          e:
                            type: string
