# this runs on any pr going to release
name: Bump Optic
on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - labeled
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Optic Repository @ Develop
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # v2.3.3
        with:
            ref: develop
            token: ${{ github.token }}
      - name: Yarn Install
        run: yarn install
      - name: Extract Label
        run: echo "LABEL=${{ github.event.label.name }}" >> $GITHUB_ENV
      - name: Determine version bump type
        run: |
          if [ "$LABEL" = "major" ]; then
            echo "TYPE=major" >> $GITHUB_ENV
          elif [ "$LABEL" = "minor" ]; then
            echo "TYPE=minor" >> $GITHUB_ENV
          elif [ "$LABEL" = "patch" ]; then
            echo "TYPE=patch" >> $GITHUB_ENV
          else
            echo "This label isn't applicable to trigger a version bump"
            echo "Not a real failure — GH Actions doesn't let me exit without failing"
            exit 1
          fi
      - name: Bump to latest version
        run: echo "VERSION=$(yarn --silent bump $TYPE)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c7f493a8000b8aeb17a1332e326ba76b57cb83eb # v3.4.1
        id: cpr
        with:
          branch: bump/bot/${{ github.run_id }}
          base: develop
          commit-message: Bumped to ${{ env.VERSION }} [ ${{ env.TYPE }} update]
          title: Bumped to ${{ env.VERSION }} [ ${{ env.TYPE }} update]
          labels: ${{ env.TYPE }}
      - name: Comment back with PR
        uses: unsplash/comment-on-pr@master # leaving this on master, the most recent tag is well behind
        env:
          GITHUB_TOKEN: ${{ secrets.COMMENT_PR }}
        with:
          msg: "Bumped to ${{ env.VERSION }} — Approve PR #${{ steps.cpr.outputs.pull-request-number }} to merge the version change"
