# Automatically builds a Release Notes Draft as PRs get merged into develop
# Configure the format of the release notes @ /.github/release-drafter.yml

name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@06d4616a80cd7c09ea3cf12214165ad6c1859e67 # https://github.com/release-drafter/release-drafter/commits/v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}