# Automatically builds a Release Notes Draft as PRs get merged into develop
# Configure the format of the release notes @ /.github/release-drafter.yml

name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3782ccd1a495040818a9e5d0e8bc4ed22d3b1361 # v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
